//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace NeqSimExcel {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(22)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet18 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox gasViscosityCommboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox oilViscosityCmboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox aqueousViscositycomboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBox3;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBox4;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBox5;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox oilCOnductivityComboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox gasCondutivityComboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox aqueousConduvtivityComboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button2;
        
        internal System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet18(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet18", "Sheet18") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet18 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.gasViscosityCommboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "1CFED2BE119AE914D4C1BB4319AF98EDDC6301", "1CFED2BE119AE914D4C1BB4319AF98EDDC6301", this, "gasViscosityCommboBox");
            this.oilViscosityCmboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "39C16115E3ACE13464D3A99537BCE670F37923", "39C16115E3ACE13464D3A99537BCE670F37923", this, "oilViscosityCmboBox");
            this.aqueousViscositycomboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "430516B774B476446064AB84455C95B7BAC694", "430516B774B476446064AB84455C95B7BAC694", this, "aqueousViscositycomboBox");
            this.comboBox3 = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "5C510AE1455D9F542EA587FD5E4EC14F5269B5", "5C510AE1455D9F542EA587FD5E4EC14F5269B5", this, "comboBox3");
            this.comboBox4 = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "67A6C00D6687E26475C6958E6D14CE9EE21C16", "67A6C00D6687E26475C6958E6D14CE9EE21C16", this, "comboBox4");
            this.comboBox5 = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "72271141F7F304743D97A5F1778C4D0587F767", "72271141F7F304743D97A5F1778C4D0587F767", this, "comboBox5");
            this.oilCOnductivityComboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "9E13BA6D292D4B946339B3CE90165787BA7C39", "9E13BA6D292D4B946339B3CE90165787BA7C39", this, "oilCOnductivityComboBox");
            this.gasCondutivityComboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "13E1C5BA71AC7C14A361AD7410D08BDB74F5C1", "13E1C5BA71AC7C14A361AD7410D08BDB74F5C1", this, "gasCondutivityComboBox");
            this.aqueousConduvtivityComboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "16D4EADA81744B14F1A18BDE1B0C049C53E8A1", "16D4EADA81744B14F1A18BDE1B0C049C53E8A1", this, "aqueousConduvtivityComboBox");
            this.button1 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1DBCC408B1A98414DB418B8514B308F95DA541", "1DBCC408B1A98414DB418B8514B308F95DA541", this, "button1");
            this.button2 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "181531CCA1CD421483118179141CC2BF4410A1", "181531CCA1CD421483118179141CC2BF4410A1", this, "button2");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            this.folderBrowserDialog1 = new System.Windows.Forms.FolderBrowserDialog();
            // 
            // gasViscosityCommboBox
            // 
            this.gasViscosityCommboBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.gasViscosityCommboBox.Items.AddRange(new object[] {
                        "polynom",
                        "friction theory",
                        "LBC",
                        "PFCT",
                        "PFCT-Heavy-Oil"});
            this.gasViscosityCommboBox.Name = "gasViscosityCommboBox";
            this.gasViscosityCommboBox.Text = "Default";
            // 
            // oilViscosityCmboBox
            // 
            this.oilViscosityCmboBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.oilViscosityCmboBox.Items.AddRange(new object[] {
                        "polynom",
                        "friction theory",
                        "LBC",
                        "PFCT",
                        "PFCT-Heavy-Oil"});
            this.oilViscosityCmboBox.Name = "oilViscosityCmboBox";
            this.oilViscosityCmboBox.Text = "Default";
            // 
            // aqueousViscositycomboBox
            // 
            this.aqueousViscositycomboBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.aqueousViscositycomboBox.Items.AddRange(new object[] {
                        "polynom",
                        "friction theory",
                        "LBC",
                        "PFCT",
                        "PFCT-Heavy-Oil"});
            this.aqueousViscositycomboBox.Name = "aqueousViscositycomboBox";
            this.aqueousViscositycomboBox.Text = "Default";
            // 
            // comboBox3
            // 
            this.comboBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.comboBox3.Items.AddRange(new object[] {
                        "Parachor",
                        "Linear Gradient Theory",
                        "Simple Gradient Theory",
                        "Full Gradient Theory",
                        "Firozabadi Ramley"});
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Text = "Default";
            // 
            // comboBox4
            // 
            this.comboBox4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.comboBox4.Items.AddRange(new object[] {
                        "Parachor",
                        "Linear Gradient Theory",
                        "Simple Gradient Theory",
                        "Full Gradient Theory",
                        "Firozabadi Ramley"});
            this.comboBox4.Name = "comboBox4";
            this.comboBox4.Text = "Default";
            // 
            // comboBox5
            // 
            this.comboBox5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.comboBox5.Items.AddRange(new object[] {
                        "Parachor",
                        "Linear Gradient Theory",
                        "Simple Gradient Theory",
                        "Full Gradient Theory",
                        "Firozabadi Ramley"});
            this.comboBox5.Name = "comboBox5";
            this.comboBox5.Text = "Default";
            // 
            // oilCOnductivityComboBox
            // 
            this.oilCOnductivityComboBox.AutoCompleteCustomSource.AddRange(new string[] {
                        "PFCT",
                        "polynom",
                        "Chung"});
            this.oilCOnductivityComboBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.oilCOnductivityComboBox.Items.AddRange(new object[] {
                        "PFCT",
                        "polynom",
                        "Chung"});
            this.oilCOnductivityComboBox.Name = "oilCOnductivityComboBox";
            this.oilCOnductivityComboBox.Text = "Default";
            // 
            // gasCondutivityComboBox
            // 
            this.gasCondutivityComboBox.AutoCompleteCustomSource.AddRange(new string[] {
                        "PFCT",
                        "polynom",
                        "Chung"});
            this.gasCondutivityComboBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.gasCondutivityComboBox.Items.AddRange(new object[] {
                        "PFCT",
                        "polynom",
                        "Chung"});
            this.gasCondutivityComboBox.Name = "gasCondutivityComboBox";
            this.gasCondutivityComboBox.Text = "Default";
            // 
            // aqueousConduvtivityComboBox
            // 
            this.aqueousConduvtivityComboBox.AutoCompleteCustomSource.AddRange(new string[] {
                        "PFCT",
                        "polynom",
                        "Chung"});
            this.aqueousConduvtivityComboBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.aqueousConduvtivityComboBox.Items.AddRange(new object[] {
                        "PFCT",
                        "polynom",
                        "Chung"});
            this.aqueousConduvtivityComboBox.Name = "aqueousConduvtivityComboBox";
            this.aqueousConduvtivityComboBox.Text = "Default";
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Name = "button1";
            this.button1.Text = "Set";
            this.button1.UseVisualStyleBackColor = false;
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Name = "button2";
            this.button2.Text = "Set";
            this.button2.UseVisualStyleBackColor = false;
            // 
            // folderBrowserDialog1
            // 
            // 
            // Sheet18
            // 
            this.gasViscosityCommboBox.BindingContext = this.BindingContext;
            this.oilViscosityCmboBox.BindingContext = this.BindingContext;
            this.aqueousViscositycomboBox.BindingContext = this.BindingContext;
            this.comboBox3.BindingContext = this.BindingContext;
            this.comboBox4.BindingContext = this.BindingContext;
            this.comboBox5.BindingContext = this.BindingContext;
            this.oilCOnductivityComboBox.BindingContext = this.BindingContext;
            this.gasCondutivityComboBox.BindingContext = this.BindingContext;
            this.aqueousConduvtivityComboBox.BindingContext = this.BindingContext;
            this.button1.BindingContext = this.BindingContext;
            this.button2.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet18 _Sheet18;
        
        internal static Sheet18 Sheet18 {
            get {
                return _Sheet18;
            }
            set {
                if ((_Sheet18 == null)) {
                    _Sheet18 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
