//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace NeqSimExcel {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(29)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet25 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button calcuateButton;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox fluidsComboBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.LinkLabel linkLabel1;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox unitOpsNamesCheckBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.LinkLabel linkLabel2;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox glycolTypeComboBox;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet25(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet25", "Sheet25") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet25 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.calcuateButton = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1F62FABC01C0701401A183A71A107BBBBCD3B1", "1F62FABC01C0701401A183A71A107BBBBCD3B1", this, "calcuateButton");
            this.fluidsComboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "2FA0185362EB642483C28B0C2E919634E93C32", "2FA0185362EB642483C28B0C2E919634E93C32", this, "fluidsComboBox");
            this.linkLabel1 = new Microsoft.Office.Tools.Excel.Controls.LinkLabel(Globals.Factory, this.ItemProvider, this.HostContext, "3B7CE220A34E453492C39F323642F8E458B603", "3B7CE220A34E453492C39F323642F8E458B603", this, "linkLabel1");
            this.unitOpsNamesCheckBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "4C9459A6C4C41B44E214B19F489A41B8FDE2B4", "4C9459A6C4C41B44E214B19F489A41B8FDE2B4", this, "unitOpsNamesCheckBox");
            this.linkLabel2 = new Microsoft.Office.Tools.Excel.Controls.LinkLabel(Globals.Factory, this.ItemProvider, this.HostContext, "53A1C41F059FDB54CBA58BFE5A4C386E5C5075", "53A1C41F059FDB54CBA58BFE5A4C386E5C5075", this, "linkLabel2");
            this.glycolTypeComboBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "68033A1B56FD05648106B2226A576DF3F7F206", "68033A1B56FD05648106B2226A576DF3F7F206", this, "glycolTypeComboBox");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // calcuateButton
            // 
            this.calcuateButton.BackColor = System.Drawing.SystemColors.Control;
            this.calcuateButton.ForeColor = System.Drawing.SystemColors.ControlText;
            this.calcuateButton.Name = "calcuateButton";
            this.calcuateButton.Text = "Calculate";
            this.calcuateButton.UseVisualStyleBackColor = false;
            // 
            // fluidsComboBox
            // 
            this.fluidsComboBox.Name = "fluidsComboBox";
            this.fluidsComboBox.Text = "Active fluid";
            // 
            // linkLabel1
            // 
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Text = "View";
            // 
            // unitOpsNamesCheckBox
            // 
            this.unitOpsNamesCheckBox.DropDownHeight = 100;
            this.unitOpsNamesCheckBox.IntegralHeight = false;
            this.unitOpsNamesCheckBox.ItemHeight = 13;
            this.unitOpsNamesCheckBox.Name = "unitOpsNamesCheckBox";
            // 
            // linkLabel2
            // 
            this.linkLabel2.Name = "linkLabel2";
            this.linkLabel2.Text = "View";
            // 
            // glycolTypeComboBox
            // 
            this.glycolTypeComboBox.Items.AddRange(new object[] {
                        "MEG",
                        "TEG",
                        "DEG"});
            this.glycolTypeComboBox.Name = "glycolTypeComboBox";
            this.glycolTypeComboBox.Text = "TEG";
            // 
            // Sheet25
            // 
            this.calcuateButton.BindingContext = this.BindingContext;
            this.fluidsComboBox.BindingContext = this.BindingContext;
            this.linkLabel1.BindingContext = this.BindingContext;
            this.unitOpsNamesCheckBox.BindingContext = this.BindingContext;
            this.linkLabel2.BindingContext = this.BindingContext;
            this.glycolTypeComboBox.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet25 _Sheet25;
        
        internal static Sheet25 Sheet25 {
            get {
                return _Sheet25;
            }
            set {
                if ((_Sheet25 == null)) {
                    _Sheet25 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
